backend:
  name: git-gateway
  branch: hugo-test

media_folder: website/static/media
public_folder: /media
publish_mode: editorial_workflow
display_url: https://austinfay.netlify.com

collections:
  - name: 'articles'
    label: 'Article'
    format: 'frontmatter'
    folder: 'website/content/articles'
    create: true
    slug: '{{title}}-{{month}}-{{day}}-{{year}}'
    editor:
      preview: true
    preview_path: 'blog/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: "Special Pages"
    name: "special"
    files:
      - label: "Home Page"
        name: "home"
        file: "website/content/home.md"
        fields:
          - {label: "Body", name: body, widget: markdown}