baseURL: "/"
languageCode: "en-us"
title: "0xAF"
copyright: "Copyright &copy; 2020 Austin Fay. All rights reserved."
publishDir: "dist"
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 3
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: rrt
    tabWidth: 4