baseURL: "/"
languageCode: "en-us"
title: "0xAF"
copyright: "Copyright &copy; 2020 Austin Fay. All rights reserved."
publishDir: "dist"
ignoreFiles: ["series/*"]
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 3
  highlight:
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: false
    noClasses: true
    style: native
    tabWidth: 4
# taxonomies:
#   series: series